//DO NOT forget to update 'LogHistogram.cs' if you change these values
#define HISTOGRAM_BINS          128
#define HISTOGRAM_TEXELS        HISTOGRAM_BINS / 4
#define HISTOGRAM_THREAD_X				16
#define HISTOGRAM_THREAD_Y				16
#define HISTOGRAM_REDUCTION_THREAD_X    HISTOGRAM_THREAD_X
#define HISTOGRAM_REDUCTION_THREAD_Y    HISTOGRAM_BINS / HISTOGRAM_THREAD_Y
#define HISTOGRAM_REDUCTION_BINS HISTOGRAM_REDUCTION_THREAD_X * HISTOGRAM_REDUCTION_THREAD_Y